firstpullrequest
The-Codesis/Hello-World pull request #1
Opened 2020-06-07 10:04 UTC by Janaki2399

2020-06-07 11:16 UTC, adiaholic requested changes

2020-06-07 11:16 UTC, adiaholic commented on code/Java/Hw.java
> +{
Looks like you are going about this workflow perfectly. However I strongly recommend using [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html) for programming in Java. In bigger organisations, code maintenance is as important as adding newer modules.
Congrats on your very first PR 😃!

2020-06-07 11:46 UTC, adiaholic commented
Squash please

2020-06-07 13:11 UTC, Janaki2399 commented
> Squash please

I tried squashing. How do I check if its squashed?

2020-06-07 14:28 UTC, Janaki2399 commented
I sqashed it

2020-06-07 14:28 UTC, Janaki2399 commented
I squashed the commits

2020-06-09 04:14 UTC, adiaholic approved these changes

2020-06-09 04:16 UTC, merged